# This file was generated by GoReleaser. DO NOT EDIT.
cask "aliasdeck" do
  version "0.5.4"

  on_macos do
    on_intel do
      sha256 "fd97f16a523e972f0a642e9d70e90f8d2a2217a048995144afce14c75e1e0e24"
      url "https://github.com/angeltonio/aliasdeck/releases/download/v#{version}/aliasdeck_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/angeltonio/aliasdeck"
    end
    on_arm do
      sha256 "d2d941435e33cb084905c2218f8b100f646147094039af766e284f6e6d492e09"
      url "https://github.com/angeltonio/aliasdeck/releases/download/v#{version}/aliasdeck_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/angeltonio/aliasdeck"
    end
  end

  on_linux do
    on_intel do
      sha256 "55d971fe1e02a6a65207961c24cbecdba3bc39dd75d0d6fb1734d26e8d9dfc12"
      url "https://github.com/angeltonio/aliasdeck/releases/download/v#{version}/aliasdeck_#{version}_linux_amd64.tar.gz",
        verified: "github.com/angeltonio/aliasdeck"
    end
    on_arm do
      sha256 "0a76eb1afb2cc8a705269ab64427829ee2c75f4b00aed3c161778dcd9b21cf68"
      url "https://github.com/angeltonio/aliasdeck/releases/download/v#{version}/aliasdeck_#{version}_linux_arm64.tar.gz",
        verified: "github.com/angeltonio/aliasdeck"
    end
  end

  name "aliasdeck"
  desc "Your commands. Every machine. Compiles neutral aliases into shell-specific syntax."
  homepage "https://github.com/angeltonio/aliasdeck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aliasdeck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/aliasdeck"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Get started with:
      aliasdeck init
      aliasdeck edit
      aliasdeck sync
  EOS
end
