# This file was generated by GoReleaser. DO NOT EDIT.
cask "aliasdeck" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "ce527de8a0500e363d81853fb9f396c22e692f88e3025623560b191162b2f3b0"
      url "https://github.com/angeltonio/aliasdeck/releases/download/v#{version}/aliasdeck_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/angeltonio/aliasdeck"
    end
    on_arm do
      sha256 "11b03d00291a18fac9a804acecb254f36ed3eee0012b595f9e51768a82a67ec0"
      url "https://github.com/angeltonio/aliasdeck/releases/download/v#{version}/aliasdeck_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/angeltonio/aliasdeck"
    end
  end

  on_linux do
    on_intel do
      sha256 "fedbb33ac380572b1a5e42b0f5e873258abd5f258b25a26a90966ee442397f6d"
      url "https://github.com/angeltonio/aliasdeck/releases/download/v#{version}/aliasdeck_#{version}_linux_amd64.tar.gz",
        verified: "github.com/angeltonio/aliasdeck"
    end
    on_arm do
      sha256 "3156e6549fab477bc7a6e494feeb41d2af17776cff72da7741a739290a5a444b"
      url "https://github.com/angeltonio/aliasdeck/releases/download/v#{version}/aliasdeck_#{version}_linux_arm64.tar.gz",
        verified: "github.com/angeltonio/aliasdeck"
    end
  end

  name "aliasdeck"
  desc "Your commands. Every machine. Compiles neutral aliases into shell-specific syntax."
  homepage "https://github.com/angeltonio/aliasdeck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aliasdeck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/aliasdeck"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Get started with:
      aliasdeck init
      aliasdeck edit
      aliasdeck sync
  EOS
end
