# This file was generated by GoReleaser. DO NOT EDIT.
cask "aliasdeck" do
  version "0.3.0"

  on_macos do
    on_intel do
      sha256 "47c728f64bdb2b7145eff1b77143369a394ed3d345e42dabe0c8a81b5d448be2"
      url "https://github.com/angeltonio/aliasdeck/releases/download/v#{version}/aliasdeck_#{version}_darwin_amd64.tar.gz",
        verified: "github.com/angeltonio/aliasdeck"
    end
    on_arm do
      sha256 "cb4d2bde7b3f58fb80870106a63a273fe4fdc9920aab6dd99f947c3fd3814c71"
      url "https://github.com/angeltonio/aliasdeck/releases/download/v#{version}/aliasdeck_#{version}_darwin_arm64.tar.gz",
        verified: "github.com/angeltonio/aliasdeck"
    end
  end

  on_linux do
    on_intel do
      sha256 "9995b068952422e00ded67a8951776ed7596e43e7c844bec16d0ee1b0f07933d"
      url "https://github.com/angeltonio/aliasdeck/releases/download/v#{version}/aliasdeck_#{version}_linux_amd64.tar.gz",
        verified: "github.com/angeltonio/aliasdeck"
    end
    on_arm do
      sha256 "4dee163fb80936053e6df40d48c9dac06613783b33c13f760df8c82c659af69f"
      url "https://github.com/angeltonio/aliasdeck/releases/download/v#{version}/aliasdeck_#{version}_linux_arm64.tar.gz",
        verified: "github.com/angeltonio/aliasdeck"
    end
  end

  name "aliasdeck"
  desc "Your commands. Every machine. Compiles neutral aliases into shell-specific syntax."
  homepage "https://github.com/angeltonio/aliasdeck"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "aliasdeck"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr",
                     args: ["-dr", "com.apple.quarantine", "#{staged_path}/aliasdeck"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Get started with:
      aliasdeck init
      aliasdeck edit
      aliasdeck sync
  EOS
end
